---
- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
  - name: Load configuration
    include_role:
      name: ekara.configuration
  - set_fact:
      ekara_plf: "{{ekara_configuration_params.environment.name}}_{{ekara_configuration_params.environment.qualifier}}"
    when:
    - ekara_plf is not defined

  tasks:
  - meta: refresh_inventory

  - name: Create inventory folder
    file:
      state: directory
      path: "{{ekara_inventory_path}}"
  - name: Gather instances
    ec2_instance_facts:
      filters:
        "tag:ek.stack_name": "{{ ekara_configuration_params.environment.name }}"
        "tag:ek.stack_qualifier": "{{ ekara_configuration_params.environment.qualifier }}"
    register: ekara_instances
  - name: Gather Worker hosts
    ec2_instance_facts:
      filters:
        "tag:ek.swarm_type": "{{ ekara_plf }}_worker"
        instance-state-name: running
    register: ekara_workers
  - name: Update local inventory
    template:
      src: templates/hosts.j2
      dest: "{{ekara_inventory_path}}/hosts"
  - name: Update nodeset inventory
    template:
      src: templates/hosts-nodeset.j2
      dest: "{{ekara_inventory_path}}/hosts-{{ekara_configuration_params.environment.nodeset}}"

  - name: Check IP configuration
    set_fact:
      ekara_public_ip: "{{ ekara_configuration_params.params.assign_public_ip | default(True) }}"
  - name: Add ssh configuration for each instance
    include_role:
      name: ekara.ssh
    vars:
      ekara_ssh_proxy:
      ekara_ssh_key: "{{ ekara_configuration_params.connectionConfig.machine_private_key }}"
      ekara_ssh_host: "{{item.private_ip_address}}"
    when:
    - ekara_public_ip == False
    - item.state.code != 48
    with_items:
    - "{{ ekara_instances.instances }}"
    loop_control:
      label: "{{ item.instance_id }}"
