---
plugin: aws_ec2
regions:
- eu-west-1
- eu-west-2
- eu-central-1
- eu-north-1 
hostnames:
- dns-name
- private-ip-address
filters:
  instance-state-code:
  - '16'
keyed_groups:
- prefix: tag
  key: tags
